apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-pipline
  name: hello-pipline
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-pipline
  template:
    metadata:
      labels:
        app: hello-pipline
    spec:
      containers:
      - name: hello-pipline
        image: 192.168.189.129:8081/wornxiao/hello-pipline:v3.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-pipline
  name: hello-pipline
  namespace: test
spec:
  selector:
    app: hello-pipline
  ports:
  - port: 8081
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: test
  name: pipeline-ingress
spec:
  ingreeClassName: ingress
  rules:
  - host: worn.pipeline.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-pipline
            port:
              number: 8081